### ISSUE TITLE
<update_date> field is always empty for all plugins in plugins.xml

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Django#188] opened 2021-08-23 17:21 UTC
This breaks the "Sort by Date Updated" functionality introduced with https://github.com/qgis/QGIS/pull/35008 in the QGIS plugins manager.
See https://github.com/qgis/QGIS/issues/44810

**Comment by sumandari** [comment] 2021-09-15 03:26
Hi @agiudiceandrea  @NyakudyaA, do you know what is the endpoint to do this sort function? Or what information should be in plugins.xml to fix the issue?

**Comment by agiudiceandrea** [comment] 2021-09-15 04:26
@sumandari the functionality was introduced in QGIS with https://github.com/qgis/QGIS/pull/35008

**Comment by agiudiceandrea** [comment] 2021-09-23 10:54
@sumandari was the provided info sufficient to fix the issue, or do you need something else?

**Comment by agiudiceandrea** [comment] 2021-09-23 10:56
Anyway, I think @suricatus could give you better insight of the issue.

**Comment by sumandari** [comment] 2021-09-24 01:24
Hi @agiudiceandrea, apologies for the delay. Thank you for providing the info, but, yes, It's not clear to me.
I hope @suricactus would let me know what the endpoint is and what data require to fix the issue?

**Comment by suricactus** [comment] 2021-09-25 13:34
Hello @sumandari . It is quite easy to see where the issue comes from with this command:
```
curl 'https://plugins.qgis.org/plugins/plugins.xml?qgis=3.20' | grep update_date -B 1
```

QGIS expects that `update_date` in the plugins XML is not empty, like it is right now. It needs to hold 1) the date the version was updated or in the worst case 2) the date the plugin was created.

**Comment by sumandari** [comment] 2021-09-27 02:41
Thank you @suricactus. Now I can see what the issue is, I will look into it

**Comment by sumandari** [comment] 2021-10-01 01:32
Re-open ticket. I will close it when it has been deployed

**Comment by sumandari** [comment] 2021-10-01 03:11
The fix has been deployed.

**Comment by agiudiceandrea** [comment] 2021-10-01 05:57
@sumandari it seems now there is something wrong with the dates in plugins.xml compared with the dates displayed in plugins.qgis.org.
Just some example:
- Mapflow
  - plugins.xml
<create_date>2021-09-29T09:23:12.996709</create_date>
<update_date>2021-09-29T09:23:13.225389</update_date>
  - plugins.qgis.org
Created on: July 9, 2021
Latest Plugin Version: Sept. 29, 2021

- ImportPhotos
  - plugins.xml
<create_date>2021-09-29T08:02:29.323220</create_date>
<update_date>2021-09-30T00:33:46.533987</update_date>
  - plugins.qgis.org
Created on: Feb. 16, 2018
Latest Plugin Version: Sept. 29, 2021

- OpenLayers Plugin
  - plugins.xml
<create_date>2018-04-09T06:39:24.116894</create_date>
<update_date>2021-09-25T10:25:28.166562</update_date>
  - plugins.qgis.org
Created on: Oct. 4, 2012
Latest Plugin Version: April 9, 2018

- QuickMapServices
  - plugins.xml
<create_date>2021-08-24T09:38:22.559787</create_date>
<update_date>2021-09-28T11:11:48.735641</update_date>
  - plugins.qgis.org
Created on: Jan. 11, 2015
Latest Plugin Version: Aug. 24, 2021

**Comment by agiudiceandrea** [comment] 2021-10-01 06:00
See https://github.com/qgis/QGIS-Django/pull/204#issuecomment-931932741

**Comment by sumandari** [comment] 2021-10-01 10:54
@agiudiceandrea @suricactus another fix has been deployed. Please kindly test it

**Comment by agiudiceandrea** [comment] 2021-10-01 11:00
@sumandari it seems now it's OK! Thank you!

**Closed** 2021-10-01 14:11 UTC
