### ISSUE TITLE
No image preview for models and 3D models and they are not downloadable

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS-Django#298] opened 2023-08-20 20:09 UTC
At https://plugins.qgis.org/models/?order_by=-upload_date&&is_gallery=true (or its 3D counterpart), all that I can see is 

![image](https://github.com/qgis/QGIS-Django/assets/7983394/a72485b2-e266-46dc-ad06-c5b12347c9c3)
And if ever I try to download any 2D or 3D models, I get:
> Error 500: internal application error.
>
>An email message with all error details has been sent to our staff that will fix the issue ASAP.

**Comment by sumandari** [comment] 2023-09-30 05:33
refer to: https://github.com/qgis/QGIS-Django/blob/20576119fe0f05a927a09f096e1072d85f7f04f6/qgis-app/templates/base/list_galery.html#L97
there is a possibility that the issue is coming from static files. 
@timlinux, @dimasciput  could you please share the log error from https://plugins.qgis.org/models/30/download/ to confirm the issue?

**Comment by agiudiceandrea** [comment] 2023-11-05 16:49
See also: https://lists.osgeo.org/pipermail/qgis-developer/2023-November/066202.html.

**Comment by Xpirix** [comment] 2024-01-24 12:01
The fix for this issue has been deployed. However, some of the processing models could not be recovered. We notified the authors about the issue and asked them to re-upload.

**Closed by Xpirix** 2024-01-24 12:01 UTC
Labels: 🕔 Size 8
