### ISSUE TITLE
The "repository" tag is not updated from metadata.txt

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#43] opened 2016-09-02 16:07 UTC
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/10142)
## Author

[Borys Jurgiel](https://hub.qgis.org/users/89) (@borysiasty)
## Description

Steps to reproduce:
1. Create a plugin with missing the "repository" tag in the metadata.txt and upload it.
2. The application complains about the missing tag of course.
3. Create a new (higher) version with that tag added to the metadata.txt and upload it.
4. The application still says that tag is missing.

Please note the "homepage" and "tracker" tags work properly.
## Comments

Akbar Gumbira (@akbargumbira)

> Hi Borys, I could not reproduce this.
> 
> After the point 2, the plugin won't get uploaded.
> 
> After changing the point 3 (whether still using the same version from point 2, or higher version), the plugin will successfully get uploaded without complaining missing repository.
> 
> Did I miss something from your description?

**Comment by olivierdalang** [comment] 2019-08-30 13:18
Hi, bug also appears when changing the repository, it won't be updated (this is the case for instance for  https://plugins.qgis.org/plugins/travel_time_platform_plugin/ , where I changed the repo at version 1, but it still displays the old repo)

**Comment by sumandari** [comment] 2020-11-30 03:13
@olivierdalang, could you please confirm if the issue still persists? I tried to reproduce your issue. I changed the repository value in metadata file and uploaded it with the new version, the application displayed the new repository instead.

**Comment by olivierdalang** [comment] 2020-12-03 12:05
Seems fixed on the plugin where I had the issue in the first place. I'll double check next time I have an update to that plugin, as the repo changed again.

**Comment by sumandari** [comment] 2020-12-03 23:56
Thanks @olivierdalang

**Comment by borysiasty** [comment] 2020-12-07 20:17
I don't have any affected plugin at hand, so feel free to close the ticket. I'll reopen it if it turns out the problem still exists.

**Closed** 2023-11-10 13:18 UTC
