### ISSUE TITLE
user image is missing from planet pages

### ISSUE THREAD

**Issue by akbargumbira** [qgis/QGIS-Django#34] opened 2016-09-02 16:06 UTC
[This issue has been migrated from the old QGIS issue tracker.](https://hub.qgis.org/issues/4508)
## Author

[Alessandro Pasotti](https://hub.qgis.org/users/15) (@elpaso)
## Description

See top right in page:
http://users.qgis.org/planet/tag/thematics/
the missing image is:
http://users.qgis.org/static//feedjack/default/img/faces/woostuff.png
which leads to 404
I'm not sure if it's just a matter of hiding the IMG tag (template stuff) if the image is missing or if this is a bug somewhere in feedjack.
## Comments

Paolo Cavallini (@pcav) :

> Assigned to set to Tim Sutton (@timlinux)

**Comment by kannes** [comment] 2018-03-19 13:55
Can't reproduce this (anymore).

**Comment by timlinux** [comment] 2023-11-10 13:13
@Xpirix see if you can reproduce and close if not

**Comment by Xpirix** [comment] 2023-11-14 06:51
@timlinux I can't reproduce this too. I will close it then.

**Closed by Xpirix** 2023-11-14 06:51 UTC
