### ISSUE TITLE
RSS feed for QGIS Planet

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS-Django#79] opened 2020-08-03 15:25 UTC
Please provide a RSS feed for QGIS Planet, as in old version
Thank you!

**Comment by lhirlimann** [comment] 2020-08-10 09:00
this is a duplicate of https://github.com/qgis/QGIS-Django/issues/56 - feed should be working right now. cc @rduivenvoorde @dimasciput

**Comment by lhirlimann** [comment] 2020-08-10 09:00
I would hav closed the issue but I don't have enough rights.

**Comment by rduivenvoorde** [comment] 2020-08-10 15:21
fixed now

**Closed by rduivenvoorde** 2020-08-10 15:21 UTC
